### ISSUE TITLE
1. General Page

### ISSUE THREAD

**Issue by damquixote** [evanbruce38/Pet-Matchmaker#1]
Description
Must Have
* Build a website where a user is prompted with criteria that matches them with compatible pets
* Images of pets must be present on each webpage
* Website must have a uniform template for all subsequent webpages
Features
* The user is prompted with information on their general location, desired pet age, sex, and size
* The hero includes hyperlinks to the homepage and a pet facts page

**Comment by devihall** [comment]
completed
